name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly set Ubuntu version

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug System Info
      run: |
        echo "Kernel Info:"
        uname -a
        echo "Ubuntu Version:"
        lsb_release -a
        echo "GCC Version:"
        gcc --version
        echo "Clang Version:"
        clang --version

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make gcc clang llvm ccache git

    - name: Build Kernel
      run: |
        make clean && make mrproper
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make defconfig
        make -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: compiled-kernel
        path: arch/arm64/boot/Image

