name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Files in Root Directory
        run: ls -la  # Debugging: Check if the kernel source exists

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/AafaqueAnjum06/GalaxyA23-NetHunter-Kernel.git kernel
          ls -la kernel  # Debugging: Check if files exist inside kernel directory

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc flex bison

      - name: Set up environment
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-

      - name: Build Kernel
        run: |
          cd kernel_source  # Ensure we are in the right directory
          make clean && make mrproper
          make defconfig
          make -j$(nproc)

