name: Kernel Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib \
          g++-aarch64-linux-gnu g++-arm-linux-gnueabi g++-arm-linux-gnueabihf \
          git libssl-dev libncurses5-dev python3 rsync unzip xz-utils zlib1g-dev

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make defconfig
        make -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: compiled-kernel
        path: arch/arm64/boot/Image.gz-dtb

