name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Root Directory
        run: |
          echo "Listing contents of root directory:"
          ls -la

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/AafaqueAnjum06/GalaxyA23-NetHunter-Kernel.git kernel
          echo "Listing contents of kernel directory after cloning:"
          ls -la kernel

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc flex bison

      - name: Set up environment
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-

      - name: Build Kernel
        run: |
          if [ -d "kernel" ]; then
            echo "Kernel directory found. Proceeding..."
            cd kernel
            ls -la  # List contents of kernel directory
            make clean && make mrproper
            make defconfig
            make -j$(nproc)
          else
            echo "Error: Kernel directory not found!"
            exit 1
          fi

