name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc flex bison

      - name: Set up environment
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-

      - name: Navigate to Kernel Source Directory
        run: |
          cd kernel/  # Change this to your actual kernel source directory
          ls -la   # Debugging: Check if files exist

      - name: Build Kernel
        run: |
          cd kernel/  # Change this to your actual kernel source directory
          make clean && make mrproper
          make defconfig
          make -j$(nproc)

